version: '2.4'

services:
    test-nginx:
        container_name: test-nginx
        build: ./docker/nginx
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.doc.rule=Host(`test.loc`)"
            - "traefik.http.routers.doc.entrypoints=web"
            - "traefik.http.routers.doc.service=test-svc"
            - "traefik.http.services.test-svc.loadbalancer.server.port=80"
        volumes:
            - ./app:/app
            - ./docker/nginx/conf/dev.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/logs:/var/log/nginx
        depends_on:
            - test-php
        networks:
            - traefik-public
        restart: always

    test-php:
        container_name: test-php
        build: docker/php
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=test.loc"
        volumes:
            - ./app:/app
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./logs/php/logs:/var/log/php
        networks:
            - traefik-public
        restart: always

    test-mysql:
        container_name: test-mysql
        build: docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./app:/app
            - ./logs/mysql:/var/lib/mysql/
        networks:
            - traefik-public
        restart: always

networks:
    traefik-public:
        external: true
